name: Go Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests and Generate Coverage
        run: |
          go test -v -coverpkg=./... -coverprofile=coverage.out ./internal/tests/unit/...
      
      - name: Display Coverage Report
        run: |
          go tool cover -func=coverage.out
